# Site settings
title: Melissa Choi
email: masechoi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Melissa Choi's portfolio website
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  maseinny

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"