# Site settings
title: Melissa Choi
email: masechoi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Melissa Choi's portfolio website
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  maseinny

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

# Portfolio Works
works:
  - image: ../images/work/tn-philliplim.jpg
    title: 3.1 Phillip Lim
    link_to: ../portfolio/phillip-lim.html
    class: pm
    desc: Project management
  - image: ../images/work/tn-draperjames.jpg
    title: Draper James
    link_to: ../portfolio/draper-james.html
    class: pm
    desc: Project Management
  - image: ../images/work/tn-djemail.jpg
    title: Draper James
    link_to: ../portfolio/dj-emails.html
    class: dev
    desc: Development for Newsletter Emails
  - image: ../images/work/tn-shopbazaar.jpg
    title: ShopBAZAAR
    link_to: ../portfolio/shopbazaar.html
    class: pm
    desc: Project management
  - image: ../images/work/lad.jpg
    title: life/after/denim
    link_to: ../portfolio/lad-sign.html
    class: other
    desc: Custom signage
  - image: ../images/work/yigal.jpg
    title: Yigal Azrouel
    link_to: ../portfolio/yigal-azrouel.html
    class: pm
    desc: Project management
  - image: ../images/work/tn-lulufrost.jpg
    title: Lulu Frost
    link_to: ../portfolio/lulu-frost.html
    class: pm
    desc: Project management
  - image: ../images/work/tn-owlsbrew.jpg
    title: Owl's Brew
    link_to: ../portfolio/owls-brew.html
    class: pm
    desc: Project management
  - image: ../images/work/tn-ondeck.jpg
    title: OnDeck
    link_to: ../portfolio/ondeck.html
    class: pm
    desc: Digital production
  - image: ../images/work/tn-spp.png
    title: Strawberry Patch Puzzles
    link_to: ../portfolio/spp.html
    class: dev
    desc: Jekyll site development
  - image: ../images/work/wuw.jpg
    title: When You Wish 
    link_to: ../portfolio/wuw-withdraw.html
    class: ux-design
    desc: Campaign creator's fund withdrawal
  - image: ../images/work/tn-ladmag.jpg
    title: life/after/denim
    link_to: ../portfolio/lad-ad.html
    class: design
    desc: Full page ad to be printed in a magazine
  - image: ../images/work/yumlist-tn.jpg
    title: Yumlist
    link_to: ../portfolio/yumlist.html
    class: dev secondary
    desc: Meteor.js sample app
  - image: ../images/work/wuw.jpg
    title: When You Wish 
    link_to: ../portfolio/wuw-login.html
    class: ux-design secondary
    desc: Sign in flow
  - image: ../images/work/tn-janegoodall.jpg
    title: Jane Goodall Chimp Call App
    link_to: ../portfolio/jane-goodall.html
    class: design secondary
    desc: Mobile UI for Jane Goodall Foundation app
  - image: ../images/work/tn-friends.jpg
    title: Friends at Hicksville
    link_to: ../portfolio/hicksville-friends.html
    class: design secondary
    desc: Commemorating our time at Hicksville
  - image: ../images/work/tn-greenmarket.jpg
    title: Grow NYC
    link_to: ../portfolio/greenmarket-photography.html
    class: other secondary
    desc: Greenmarket photographer
  - image: ../images/work/tn-cashtag.jpg
    title: Cashtag
    link_to: ../portfolio/cashtag.html
    class: dev secondary
    desc: Development for landing pages
  - image: ../images/work/dell.jpg
    title: Dell Social Innovation Challenge
    link_to: ../portfolio/dsic.html
    class: ux-design secondary
    desc: DSIC crowdfunding login UI
  - image: ../images/work/pg.jpg
    title: Pagegrove
    link_to: ../portfolio/pagegrove-ad.html
    class: design secondary
    desc: Flyer Ad
  - image: ../images/work/tn-parallaxstory.png
    title: Story Page
    link_to: ../portfolio/story.html
    class: dev secondary
    desc: Development of an interactive story page
  - image: ../images/portfolio/SES-front.jpg
    title: Solar Electric Scooter
    link_to: ../portfolio/story.html
    class: design secondary
    desc: Postcard flyer design
  - image: ../images/work/wuw.jpg
    title: When You Wish 
    link_to: ../portfolio/wuw-payment.html
    class: ux-design secondary
    desc: Crowdfunding sponsor process
  - image: ../images/work/dse.jpg
    title: Digital Signage Expo 2014
    link_to: ../portfolio/dse.html
    class: dev secondary
    desc: Event brochure site